#!/bin/bash

################################################################################
#                      ____        _                                           #
#                     / __ \      (_)                                          #
#                    | |  | |_ __  _  ___  _ __                                #
#                    | |  | | '_ \| |/ _ \| '_ \                               #
#                    | |__| | | | | | (_) | | | |                              #
#                     \____/|_| |_|_|\___/|_|_|_|                              #
#                    / ____| |             | |                                 #
#                   | |    | |__   ___  ___| | _____ _ __                      #
#                   | |    | '_ \ / _ \/ __| |/ / _ \ '__|                     #
#                   | |____| | | |  __/ (__|   <  __/ |                        #
#                    \_____|_| |_|\___|\___|_|\_\___|_|                        #
#                                                                              #
# Easily organize your file with multiple links from Tor Network and test      #
# if they are online.                                                          #
# Developer: Jesus 'Jay-C'                                                     #
# GitHub Page: https://github.com/JesusFromHellz/                              #
# Sistema base: Debian Jessie                                                  #
# Dependências: tor   torsocks  curl                                           #
################################################################################


banner () { #Simplesmente exibe o banner da aplicação
  echo ""
  echo ""
  echo ""
  echo ""
  echo ""
  echo ""
  echo "Be welcome to the ..."
  echo ""
  echo ".d88888b.            d8b";
  echo "d88P\" \"Y88b          Y8P";
  echo "888     888";
  echo "888     888 88888b.  888  .d88b.  88888b.";
  echo "888     888 888 \"88b 888 d88\"\"88b 888 \"88b";
  echo "888     888 888  888 888 888  888 888  888";
  echo "Y88b. .d88P 888  888 888 Y88..88P 888  888";
  echo  " \"Y88888P\"  888  888 888  \"Y88P\"  888  888";
  echo "";
  echo "";
  echo "                                                                 888";
  echo " .d8888b.  888                        888                        888";
  echo "d88P  Y88b 888                        888                        888";
  echo "888    888 888                        888                        888";
  echo "888        88888b.   .d88b.   .d8888b 888  888  .d88b.  888d888  888";
  echo "888        888  88b d8P  Y8b d88P\"    888 .88P d8P  Y8b 888P     888";
  echo "888    888 888  888 88888888 888      888888K  88888888 888 ";
  echo "Y88b  d88P 888  888 Y8b.     Y88b.    888 \"88b Y8b.     888      d8p";
  echo " \"Y8888P\"  888  888  \"Y8888   \"Y8888P 888  888  \"Y8888  888      Y8P"
  echo ""
  sleep 2;
  echo "" && sleep 0.1
  echo "" && sleep 0.1
  echo "" && sleep 0.1
  echo "" && sleep 0.1
  echo "" && sleep 0.1
  echo "" && sleep 0.1
  echo "" && sleep 0.1
  echo "" && sleep 0.1
  echo "Developer: Jesus 'Jay-C'"
  echo "" && sleep 0.1
  echo "GitHub page: https://github.com/JesusFromHellz"
  echo "" && sleep 0.1
  echo "" && sleep 0.1
  echo "" && sleep 0.1
  echo "" && sleep 0.1
}
#Início das variáveis globais
tore=""
#Fim das variáveis globais
checktor () { #Checa se o tor está presente no computador.
  tor --help 1> /dev/null 2> /dev/null
  if [ "$?" == "127" ]; then
    tore="n"
  else
    tore="y"
  fi
}
stor () { #Exibe a existência ou não do Tor para o usuário
  if [ "$tore" == "n" ]; then
    echo -e "\nQue pena, o Tor não está instalado no seu computador. "
    echo -e "Para instalá-lo, digite:"
    echo -e "apt-get install tor\n"
  else
    echo -e "\nParabéns, o Tor está corretamente instalado no seu "
    echo -e "computador. Assim sendo, poderá usufruir 100% desse"
    echo -e "programa.\n"
  fi
}
linkorg () { #Organiza um arquivo contendo links passados pelo usuário
  link="$1" #Parametro 01 da flag, arquivo origem
  dest="$2"  #Parametro 02 da flag, arquivo destino
  if [ "$link" == "" ]; then
      echo "Uso: `basename $0` [-l|--link-org] [arquivo a ser organizado] \
   [arquivo destino]"
   else
    banner;
    cat "$link" | sed -r 's/^(.*)http:\/\/(.*\.onion).*$/\2/' | sed '/^$/d' |\
    sed -n '/\.onion/p' | sed -r 's/^(.*)\.(.*\.onion).*$/\2/' |\
    sed -r 's/^(.*)-.*(.*\.onion).*$/\2/' | sed '/^.onion$/d' > "$dest"
  fi
}

help () { #Imprime ajuda, padrão exibido se nenhuma flag é passada pro comando
  echo '' #ou se a flag -h | --help é passada.
  echo 'Olá! Seja bem-vindo(a) ao tópico de ajuda do Onion Checker.'
  echo 'Com esse software você poderá checar se links onion estão '
  echo 'funcionando. Abaixo você pode ver a lista de comandos dis-'
  echo 'poníveis.'
  echo 'Se algum comando precisar de argumento e não for dado, o  '
  echo 'mesmo apresentará a mensagem do uso correto.'
  echo ''
  echo '-h ou --help            Mostra essa mensagem de ajuda;'
  echo '-l ou --link-org        Organiza os links de um arquivo;'
  echo '-b ou --banner          Exibe o banner e sai;'
  echo '-c ou --check-tor       Checa a existência do Tor no computador;'
  echo ''
}

#Testes condicionais de flags, acerca do uso do programa
if [ "$*" == "-h" ] || [ "$*" == "--help" ] || [ "$*" == "" ];
  then
    help;
  else
    case "$1" in
    -l | --link-org       ) linkorg "$2" "$3"; shift 2             ;;
    -b | --banner         ) banner; exit 0;  shift;                ;;
    -c | --check-tor      ) checktor; stor;                        ;;

    esac
fi
